'use strict';
const sources={
 history:['História da fantasia','https://en.wikipedia.org/wiki/History_of_fantasy'],
 tolkien:['Tolkien: carta a W. H. Auden, 1955','https://www.tolkienestate.com/letters/letter-to-the-poet-w-h-auden-7-jun-1955/'],
 tolkienBio:['Tolkien: vida e influências','https://en.wikipedia.org/wiki/J._R._R._Tolkien'],
 rings:['Tolkien Estate: O Senhor dos Anéis','https://www.tolkienestate.com/writing/the-lord-of-the-rings/'],
 leguin:['Le Guin: influências literárias e filosóficas','https://en.wikipedia.org/wiki/Ursula_K._Le_Guin#Influences'],
 earthsea:['Bibliografia oficial de Ursula K. Le Guin','https://www.ursulakleguin.com/bibliography'],
 brooks:['Terry Brooks: Why I Write About Elves','https://singjupost.com/why-i-write-about-elves-terry-brooks-transcript/'],
 wheel:['A Roda do Tempo: desenvolvimento da série','https://en.wikipedia.org/wiki/The_Wheel_of_Time'],
 sanderson:['Brandon Sanderson sobre Robert Jordan','https://www.brandonsanderson.com/blogs/blog/robert-jordan-tenth-year-commemoration'],
 williams:['Memory, Sorrow and Thorn: legado','https://en.wikipedia.org/wiki/Memory,_Sorrow,_and_Thorn#Legacy'],
 martin:['George R. R. Martin: pesquisa histórica','https://georgerrmartin.com/for-fans/faq/'],
 druon:['George R. R. Martin sobre Os Reis Malditos','https://grrm.livejournal.com/316785.html'],
 appendix:['Apêndice N: referências literárias de D&D','https://en.wikipedia.org/wiki/Appendix_N'],
 dnd:['As origens de Dungeons & Dragons','https://www.theguardian.com/games/2024/apr/11/it-crawled-from-below-50-years-ago-how-the-150m-dungeons-dragons-empire-began-in-a-basement'],
 realms:['Forgotten Realms: história do cenário','https://en.wikipedia.org/wiki/Forgotten_Realms'],
 warcraft:['Patrick Wyatt sobre a criação de Warcraft','https://www.wizwords.net/warcraft'],
 witcher:['The Witcher: obras e influências','https://en.wikipedia.org/wiki/The_Witcher'],
 dunsany:['Lord Dunsany: obra e legado','https://en.wikipedia.org/wiki/Lord_Dunsany'],
 dragonlance:['Dragonlance: criação e publicações','https://en.wikipedia.org/wiki/Dragonlance'],
 rpg:['História dos RPGs eletrônicos ocidentais','https://en.wikipedia.org/wiki/History_of_Western_role-playing_video_games'],
 warhammer:['Warhammer Fantasy: o universo','https://en.wikipedia.org/wiki/Warhammer_Fantasy_(setting)'],
 dragonquest:['Dragon Quest e suas influências','https://www.polygon.com/review/478796/dragon-quest-3-hd-2d-remake']
};
const nodes={
 roots:{title:'Mitos & folclore',author:'Uma herança de muitas culturas',date:'Tradições antigas',tone:'root',kind:'Raízes culturais',body:'Muito antes de a fantasia se tornar um gênero editorial, mitos, epopeias, contos orais e lendas já narravam encontros com o extraordinário. Essas tradições continuam sendo reinventadas. Elas não formam uma única linhagem universal: este mapa seleciona caminhos ligados sobretudo à fantasia ocidental.',refs:['history']},
 epic:{title:'Épicos & sagas',author:'Beowulf · Eddas · Kalevala',date:'Fontes tradicionais',tone:'root',kind:'Tradição heroica',body:'Heróis, monstros, jornadas, destinos trágicos e histórias de povos inteiros alimentam a tradição épica. Tolkien estudou literatura medieval e reconheceu o papel do Kalevala na formação de seu legendário. O Kalevala foi publicado no século XIX a partir de poesia tradicional finlandesa.',refs:['tolkien','history']},
 fairy:{title:'Contos de fadas',author:'Tradição oral e literatura',date:'Muitas épocas',tone:'fairy',kind:'Tradição feérica',body:'Transformações, encantamentos, pactos, provas e passagens para outros mundos são parte de uma tradição que atravessa séculos. A fantasia literária retoma e transforma esse repertório. As linhas pontilhadas indicam essa herança ampla, e não a influência de um único livro.',refs:['history']},
 wonder:{title:'O maravilhoso',author:'Mitos e mundos imaginados',date:'Muitas épocas',tone:'myth',kind:'Tradição cultural',body:'Relatos de deuses, reinos impossíveis e lugares fabulosos sustentam diferentes formas de narrativa maravilhosa. Aqui, o ramo reúne parte desse repertório para situar Lord Dunsany. É uma organização didática, não uma afirmação de que todas essas tradições têm a mesma origem.',refs:['history','dunsany']},
 morris:{title:'William Morris',author:'O Poço no Fim do Mundo',date:'1896',tone:'epic',kind:'Precursor literário',body:'Morris escreveu aventuras em mundos imaginários com linguagem e atmosfera inspiradas nos romances medievais. Foi um precursor importante da fantasia de mundos secundários e uma das influências literárias de Tolkien.',refs:['history','tolkienBio']},
 macdonald:{title:'George MacDonald',author:'Phantastes · A Princesa e o Goblin',date:'1858 · 1872',tone:'fairy',kind:'Precursor literário',body:'MacDonald combinou imaginação feérica, experiências espirituais e jornadas de transformação. Sua obra exerceu profunda influência em C. S. Lewis. A fantasia moderna para crianças e adultos deve muito a esse ramo anterior a Tolkien.',refs:['history']},
 aliceoz:{title:'Alice & Oz',author:'Lewis Carroll · L. Frank Baum',date:'1865 · 1900',tone:'fairy',kind:'Dois caminhos literários',body:'Alice no País das Maravilhas e O Maravilhoso Mágico de Oz são marcos distintos da fantasia. Estão agrupados para representar caminhos que exploram o absurdo, o encantamento e a viagem a outros mundos. O agrupamento não afirma que uma obra descende diretamente da outra.',refs:['history']},
 dunsany:{title:'Lord Dunsany',author:'Os Deuses de Pegāna',date:'1905',tone:'myth',kind:'Precursor literário',body:'Dunsany criou deuses e mundos próprios em uma prosa evocativa e mítica. Sua obra influenciou as narrativas oníricas de Lovecraft e foi uma leitura formadora para Ursula K. Le Guin.',refs:['dunsany','leguin']},
 tolkien:{title:'Terra-média',author:'J. R. R. Tolkien',date:'1937 · 1954–55',tone:'epic',kind:'Fantasia épica',body:'O Hobbit e O Senhor dos Anéis tornaram a Terra-média uma referência para a fantasia moderna. Tolkien reuniu linguística, mitologia, literatura medieval e invenção própria. Sua influência é enorme, mas outras linhagens da fantasia existiam antes e continuam ao lado dela.',refs:['rings','tolkien']},
 narnia:{title:'Nárnia',author:'C. S. Lewis',date:'1950–1956',tone:'fairy',kind:'Fantasia de portal',body:'Crianças atravessam do mundo cotidiano para Nárnia, onde encontram animais falantes, magia e conflitos morais. Lewis combinou a tradição dos contos de fadas, mitologias e sua imaginação cristã. George MacDonald foi uma influência central; Nárnia possui seu próprio caminho literário.',refs:['history']},
 lovecraft:{title:'Ciclo dos sonhos',author:'H. P. Lovecraft',date:'A partir de 1919',tone:'myth',kind:'Fantasia onírica',body:'Parte da obra de Lovecraft explora terras de sonho e cidades impossíveis. Esse aspecto de sua escrita recebeu forte influência de Dunsany. O nó trata desse ramo onírico, e não de reduzir toda a obra de Lovecraft a fantasia ou a uma única influência.',refs:['dunsany']},
 tao:{title:'Antropologia & taoismo',author:'Culturas, equilíbrio e alteridade',date:'Outras influências',tone:'history',kind:'Ideias e modos de pensar',body:'Uma genealogia literária também recebe contribuições de fora da literatura. A formação de Le Guin em contato com a antropologia e seu interesse pelo taoismo ajudam a explicar sua atenção à diversidade cultural e ao equilíbrio em Terramar.',refs:['leguin']},
 earthsea:{title:'Terramar',author:'Ursula K. Le Guin',date:'Primeiro romance: 1968',tone:'myth',kind:'Fantasia e amadurecimento',body:'Em um arquipélago onde palavras e nomes têm poder, Terramar explora responsabilidade, equilíbrio, identidade e mudança. Le Guin leu Dunsany e reconheceu Tolkien como influência estilística, mas construiu uma obra própria, também marcada pela antropologia e pelo taoismo. Seu primeiro romance antecede D&D.',refs:['earthsea','leguin']},
 brooks:{title:'Shannara',author:'Terry Brooks',date:'A partir de 1977',tone:'epic',kind:'Fantasia épica',body:'A Espada de Shannara é um marco da expansão comercial da fantasia épica após Tolkien. Brooks reconhece essa influência, mas sua série desenvolveu personagens, eras e conflitos próprios ao longo dos livros.',refs:['brooks']},
 jordan:{title:'A Roda do Tempo',author:'Robert Jordan',date:'A partir de 1990',tone:'epic',kind:'Fantasia épica',body:'Jordan parte de alguns elementos familiares aos leitores de Tolkien e expande sua saga com ciclos históricos, profecias, política e mitologias de diferentes culturas. Brandon Sanderson, influenciado por Jordan, mais tarde concluiu os últimos volumes da série a partir do material deixado pelo autor.',refs:['wheel','sanderson']},
 williams:{title:'Memory, Sorrow & Thorn',author:'Tad Williams',date:'1988–1993',tone:'epic',kind:'Fantasia épica',body:'A série de Tad Williams conversa com a tradição épica de Tolkien e reexamina seus motivos. George R. R. Martin a reconheceu como uma das inspirações para escrever sua própria saga de fantasia.',refs:['williams']},
 sanderson:{title:'Cosmere',author:'Brandon Sanderson',date:'A partir de 2005',tone:'epic',kind:'Universo literário',body:'O Cosmere conecta mundos de obras como Elantris, Mistborn e Os Relatos da Guerra das Tempestades. Sanderson destaca a influência de Robert Jordan em sua formação como escritor. A seta representa essa aprendizagem literária: o Cosmere e A Roda do Tempo são universos distintos.',refs:['sanderson']},
 historical:{title:'História medieval',author:'Pesquisa e romance histórico',date:'Fontes históricas',tone:'history',kind:'Influência exterior ao gênero',body:'Disputas dinásticas, instituições, guerras e vida cotidiana oferecem material para a fantasia. Martin explica que pesquisou extensamente o mundo medieval. Esse ramo lembra que as influências de uma obra não precisam vir apenas de outras fantasias.',refs:['martin']},
 druon:{title:'Os Reis Malditos',author:'Maurice Druon',date:'A partir de 1955',tone:'history',kind:'Romance histórico',body:'A série de romances históricos de Druon acompanha intrigas e disputas de poder da monarquia francesa. Martin a destacou como uma referência importante. Ela está no mapa como influência sobre a fantasia, e não como obra do gênero fantástico.',refs:['druon']},
 martin:{title:'Gelo & Fogo',author:'George R. R. Martin',date:'A partir de 1996',tone:'epic',kind:'Fantasia política e épica',body:'As Crônicas de Gelo e Fogo combinam o diálogo com Tolkien, a inspiração em Tad Williams, o romance histórico e a pesquisa medieval. A multiplicidade de entradas neste nó é intencional: uma obra reúne várias heranças. Game of Thrones é uma adaptação televisiva dessa série literária.',refs:['williams','druon','martin']},
 folk:{title:'Folclore & contos',author:'Releituras da tradição europeia',date:'Fontes tradicionais',tone:'root',kind:'Herança cultural',body:'Contos de fadas, lendas, monstros e tradições europeias continuam a ser reinterpretados por escritores modernos. No caso de The Witcher, é importante não reduzir todo o repertório ao folclore eslavo: Sapkowski dialoga com diferentes tradições e com a própria literatura de fantasia.',refs:['witcher']},
 witcher:{title:'The Witcher',author:'Andrzej Sapkowski',date:'Primeiro conto: 1986',tone:'myth',kind:'Fantasia e releitura do folclore',body:'As histórias de Geralt revisitam monstros, contos conhecidos e dilemas morais. Seus livros deram origem a adaptações e expansões em outras mídias, incluindo os jogos. Não é necessário passar por D&D para explicar a origem dessa obra.',refs:['witcher']},
 pulp:{title:'Espada & feitiçaria',author:'Howard · Leiber · Vance · Moorcock',date:'Décadas de 1930–60',tone:'game',kind:'Referências literárias de D&D',body:'Conan, Fafhrd e o Gatuno Cinzento, A Terra Moribunda e Elric são referências distintas que ajudaram a formar a imaginação do RPG. Vance influenciou a magia; Moorcock e Poul Anderson, o eixo Ordem e Caos. Este agrupamento reúne tradições pulp, espada e feitiçaria e obras próximas, sem tratá-las como um gênero homogêneo.',refs:['appendix']},
 wargames:{title:'Jogos de guerra',author:'Mesa, miniaturas e simulação',date:'Antes de 1974',tone:'history',kind:'Tradição de jogos',body:'D&D também nasceu da experimentação com jogos de guerra. Grupos de jogadores passaram a explorar personagens individuais e campanhas abertas. Os jogos de miniaturas seguiram seus próprios caminhos, entre eles Warhammer Fantasy.',refs:['dnd','warhammer']},
 chainmail:{title:'Chainmail & Blackmoor',author:'Regras de combate e campanha',date:'Início dos anos 1970',tone:'game',kind:'Antecedentes de D&D',body:'Chainmail forneceu regras de combate medieval e fantasia. Dave Arneson desenvolveu Blackmoor como uma campanha centrada em personagens e exploração. Essa convergência, junto ao trabalho de Gary Gygax, está na origem de Dungeons & Dragons. Os dois nomes não representam produtos idênticos.',refs:['dnd']},
 dnd:{title:'Dungeons & Dragons',author:'Gary Gygax · Dave Arneson',date:'1974',tone:'game',kind:'RPG de mesa',body:'D&D combinou tradições de jogos de guerra com muitas referências da literatura fantástica. Transformou aventuras em uma experiência coletiva de interpretação e regras. Influenciou outros jogos e livros, mas não é o ancestral de toda a fantasia moderna.',refs:['dnd','appendix']},
 dragonlance:{title:'Dragonlance',author:'Aventuras, cenário e romances',date:'A partir de 1984',tone:'game',kind:'Universo de D&D',body:'Dragonlance foi desenvolvido como um projeto de aventuras de RPG e ficção ambientado em Krynn. Os romances de Margaret Weis e Tracy Hickman tornaram-se parte importante dessa experiência. A conexão indica uma criação dentro do ecossistema de D&D.',refs:['dragonlance']},
 realms:{title:'Forgotten Realms',author:'Ed Greenwood',date:'Como cenário de D&D: 1987',tone:'game',kind:'Cenário incorporado a D&D',body:'Greenwood já criava histórias dos Reinos Esquecidos antes de sua publicação como cenário oficial de D&D em 1987. Portanto, a seta representa a incorporação e expansão no jogo, não a invenção inicial do mundo. Baldur’s Gate se passa nesse cenário.',refs:['realms']},
 baldurs:{title:'Baldur’s Gate',author:'Série de RPGs eletrônicos',date:'A partir de 1998',tone:'game',kind:'Jogos em Forgotten Realms',body:'Baldur’s Gate leva regras, criaturas e histórias ligadas a D&D para o computador, dentro de Forgotten Realms. É uma relação de adaptação e expansão de um cenário existente, diferente de uma influência literária genérica.',refs:['realms']},
 computer:{title:'Ultima & Wizardry',author:'Primeiras linhagens digitais',date:'1981',tone:'game',kind:'RPGs eletrônicos',body:'Essas séries ajudaram a estabelecer linguagens dos RPGs eletrônicos, dialogando com o RPG de mesa e outras experiências computacionais. Elas não abrangem todos os videogames, mas são marcos importantes nessa linhagem específica.',refs:['rpg']},
 dragonquest:{title:'Dragon Quest',author:'Yuji Horii e equipe',date:'1986',tone:'game',kind:'RPG japonês',body:'Dragon Quest combinou influências de Ultima e Wizardry em uma experiência de RPG para consoles. Esse cruzamento mostra como ideias viajam entre mídias e países e ganham formas próprias.',refs:['dragonquest']},
 warhammer:{title:'Warhammer Fantasy',author:'Games Workshop',date:'1983',tone:'game',kind:'Jogo de miniaturas e universo',body:'Warhammer Fantasy surgiu no contexto dos jogos de miniaturas e reuniu várias influências da fantasia. Sua estética influenciou Warcraft. Trata-se do ramo de fantasia de Warhammer; Warhammer 40,000 é outro universo.',refs:['warhammer','warcraft']},
 warcraft:{title:'Warcraft',author:'Blizzard',date:'1994',tone:'game',kind:'Universo de videogames',body:'Warcraft recebeu influência de Tolkien e uma forte influência visual de Warhammer, conforme o desenvolvedor Patrick Wyatt. Não é uma adaptação licenciada de Warhammer. A jogabilidade também deve a jogos de estratégia como Dune II, uma relação fora do foco literário deste mapa.',refs:['warcraft']}
};
const pos=(id,d,m)=>({id,d,m});
const edge=(from,to,type='influence',note='Uma das influências desta obra.')=>({from,to,type,note});
const chapters={
 roots:{title:'Antes dos mundos modernos',description:'Das narrativas tradicionais à construção de novos universos.',positions:[pos('roots',[1,0,2],[0,0,2]),pos('epic',[0,1],[0,1]),pos('fairy',[1,1],[1,1]),pos('wonder',[2,1],[0,4]),pos('aliceoz',[3,1],[1,4]),pos('morris',[0,2],[0,2]),pos('macdonald',[1,2],[1,2]),pos('dunsany',[2,2],[0,5]),pos('tao',[3,3],[1,5]),pos('tolkien',[0,3],[0,3]),pos('narnia',[1,3],[1,3]),pos('lovecraft',[2,3],[0,6]),pos('earthsea',[2,4,2],[1,7])],edges:[edge('roots','epic','tradition','Herança de mitos e narrativas heroicas.'),edge('roots','fairy','tradition','Transmissão e reinvenção de narrativas tradicionais.'),edge('roots','wonder','tradition','Um agrupamento cultural amplo, não uma linhagem única.'),edge('epic','morris','tradition','Recriação literária da tradição medieval.'),edge('epic','tolkien','influence','Literatura medieval e mitologia na formação da Terra-média.'),edge('morris','tolkien','influence','Morris foi uma das referências literárias de Tolkien.'),edge('fairy','macdonald','tradition','Reinvenção da imaginação feérica.'),edge('fairy','aliceoz','tradition','Caminhos distintos da literatura do maravilhoso.'),edge('macdonald','narnia','influence','MacDonald foi uma influência central para C. S. Lewis.'),edge('wonder','dunsany','tradition','Invenção de deuses e mundos em diálogo com o maravilhoso.'),edge('dunsany','lovecraft','influence','Influência especialmente nas narrativas oníricas.'),edge('dunsany','earthsea','influence','Dunsany foi uma leitura formadora para Le Guin.'),edge('tolkien','earthsea','influence','Le Guin reconheceu uma influência estilística de Tolkien.'),edge('tao','earthsea','influence','Diversidade cultural, equilíbrio e responsabilidade.') ]},
 modern:{title:'Novas vozes, novas formas de imaginar',description:'A herança épica encontra a história, o folclore e outras visões de mundo.',positions:[pos('tolkien',[1,0,2],[0,0,2]),pos('brooks',[0,1],[0,1]),pos('jordan',[1,1],[1,1]),pos('williams',[2,1],[0,2]),pos('sanderson',[1,2],[1,2]),pos('historical',[0,3],[0,3]),pos('druon',[1,3],[0,4]),pos('martin',[2,3],[1,4]),pos('folk',[3,1],[1,3]),pos('witcher',[3,2],[1,5])],edges:[edge('tolkien','brooks','influence','Brooks reconhece Tolkien entre suas grandes influências.'),edge('tolkien','jordan','influence','Diálogo com a fantasia épica e seus motivos.'),edge('tolkien','williams','influence','Releitura da tradição épica de Tolkien.'),edge('tolkien','martin','influence','Martin dialoga com a obra e as escolhas narrativas de Tolkien.'),edge('jordan','sanderson','influence','Sanderson reconhece Jordan como referência de formação.'),edge('williams','martin','influence','Williams ajudou a inspirar Martin a escrever a saga.'),edge('historical','druon','tradition','Romance construído a partir da história francesa.'),edge('historical','martin','influence','Pesquisa sobre o mundo medieval.'),edge('druon','martin','influence','Intrigas dinásticas e a tradição do romance histórico.'),edge('folk','witcher','tradition','Releitura de contos e tradições de diferentes origens.')]},
 games:{title:'Quando os mundos se tornam jogáveis',description:'Literatura e jogos de mesa se cruzam — e chegam aos videogames.',positions:[pos('tolkien',[0,0],[0,0]),pos('pulp',[1,0,2],[1,0]),pos('wargames',[3,0],[1,1]),pos('chainmail',[3,1],[1,2]),pos('dnd',[1,2,2],[0,3,2]),pos('warhammer',[3,2],[1,4]),pos('dragonlance',[0,3],[0,4]),pos('realms',[1,3],[0,5]),pos('computer',[2,3],[0,6]),pos('warcraft',[3,3],[1,6]),pos('baldurs',[1,4],[1,5]),pos('dragonquest',[2,4],[0,7])],edges:[edge('tolkien','dnd','influence','Uma das referências do repertório de povos e criaturas.'),edge('pulp','dnd','influence','Aventuras, magia e conceitos de múltiplos autores.'),edge('wargames','chainmail','tradition','Experimentação com combate e personagens individuais.'),edge('chainmail','dnd','influence','Regras e campanhas na origem de D&D.'),edge('dnd','dragonlance','expansion','Aventuras e romances criados no ecossistema de D&D.'),edge('dnd','realms','expansion','Incorporação ao D&D; o mundo já existia nas histórias de Greenwood.'),edge('realms','baldurs','expansion','Jogos ambientados em Forgotten Realms.'),edge('dnd','computer','influence','Conceitos do RPG de mesa passam aos RPGs eletrônicos.'),edge('computer','dragonquest','influence','Ultima e Wizardry inspiraram a criação de Dragon Quest.'),edge('wargames','warhammer','tradition','Desenvolvimento de jogos com exércitos de miniaturas.'),edge('warhammer','warcraft','influence','Influência visual declarada por Patrick Wyatt.'),edge('tolkien','warcraft','influence','Tolkien também foi uma inspiração direta.') ]}
};
let current='roots',lastTrigger=null;
const tree=document.getElementById('tree'),nodeContainer=document.getElementById('nodes'),svg=document.getElementById('connections'),dialog=document.getElementById('detail');
const mobile=window.matchMedia('(max-width:760px)');
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){
 const chapter=chapters[current];
 document.getElementById('chapter-title').textContent=chapter.title;
 document.getElementById('chapter-description').textContent=chapter.description;
 document.getElementById('tree-panel').setAttribute('aria-labelledby','tab-'+current);
 const positions=[...chapter.positions].sort((a,b)=>{let p=mobile.matches?a.m:a.d,q=mobile.matches?b.m:b.d;return p[1]-q[1]||p[0]-q[0];});
 nodeContainer.innerHTML=positions.map(p=>{const n=nodes[p.id],[col,row,span=1]=mobile.matches?p.m:p.d;return `<button class="node tone-${n.tone} ${span>1?'is-featured':''}" data-id="${p.id}" style="grid-column:${col+1}/span ${span};grid-row:${row+1}" aria-label="${safe(n.title)}. ${safe(n.author)}. Ver contexto e materiais para ler, assistir ou jogar."><span class="node-meta"><span>${safe(n.date)}</span><b aria-hidden="true">↗</b></span><span class="node-title">${safe(n.title)}</span><span class="node-author">${safe(n.author)}</span><span class="node-materials">${safe(materialSummary(p.id))}<span aria-hidden="true">→</span></span></button>`;}).join('');
 requestAnimationFrame(drawConnections);
}
function drawConnections(){
 const b=tree.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${b.width} ${b.height}`);
 let markup='<defs><marker id="arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 8 4 L 0 8" fill="none" stroke="#899a9f" stroke-width="1.1"/></marker></defs>';
 chapters[current].edges.forEach((e,i)=>{
 const a=nodeContainer.querySelector(`[data-id="${e.from}"]`).getBoundingClientRect(),z=nodeContainer.querySelector(`[data-id="${e.to}"]`).getBoundingClientRect();
 let x1=a.left+a.width/2-b.left,y1=a.bottom-b.top,x2=z.left+z.width/2-b.left,y2=z.top-b.top;
 let path;
 if(Math.abs(a.top-z.top)<20){const right=z.left>a.left;x1=(right?a.right:a.left)-b.left;y1=a.top+a.height/2-b.top;x2=(right?z.left:z.right)-b.left;y2=z.top+z.height/2-b.top;let mid=(x1+x2)/2;path=`M${x1},${y1} C${mid},${y1} ${mid},${y2} ${x2},${y2}`;}
 else if(z.top-a.bottom>160){const side=a.left<z.left?1:-1;const lane=(side>0?a.right-b.left+10+(i%3)*3:a.left-b.left-10-(i%3)*3);path=`M${x1},${y1} C${x1},${y1+22} ${lane},${y1+22} ${lane},${y1+38} L${lane},${y2-28} C${lane},${y2-10} ${x2},${y2-20} ${x2},${y2}`;}
 else{const mid=y1+(y2-y1)/2;path=`M${x1},${y1} C${x1},${mid} ${x2},${mid} ${x2},${y2}`;}
 markup+=`<path class="edge ${e.type}" data-from="${e.from}" data-to="${e.to}" d="${path}" marker-end="url(#arrow)"/>`;
 });svg.innerHTML=markup;
}
function chooseChapter(id,focus=false){if(!chapters[id])return;current=id;document.querySelectorAll('[role=tab]').forEach(t=>{const active=t.dataset.chapter===id;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;if(active&&focus)t.focus();});render();document.getElementById('announcement').textContent=chapters[id].title;}
function allEdges(){const seen=new Set();return Object.values(chapters).flatMap(c=>c.edges).filter(e=>{const key=e.from+'-'+e.to;if(seen.has(key))return false;seen.add(key);return true;});}
function relationMarkup(edges,incoming){return edges.map(e=>{const id=incoming?e.from:e.to;return `<button class="relation" data-related="${id}"><span class="relation-title">${safe(nodes[id].title)} <span aria-hidden="true">↗</span></span><span class="relation-note">${safe(e.note)}</span></button>`;}).join('');}
function materialSummary(id){
 const kinds=new Set((materials[id]||[]).map(m=>m.kind)),labels=[];
 if(kinds.has('Livro')||kinds.has('Manual'))labels.push('Ler');
 if(kinds.has('Filme')||kinds.has('Série')||kinds.has('Vídeo'))labels.push('Assistir');
 if(kinds.has('Jogo'))labels.push('Jogar');
 return labels.join(' · ');
}
function materialsMarkup(id){
 const list=materials[id]||[];
 if(!list.length)return '';
 const groups=[['Filmes',['Filme']],['Séries',['Série']],['Livros e manuais',['Livro','Manual']],['Jogos',['Jogo']],['Vídeos',['Vídeo']]];
 const markup=groups.map(([label,kinds])=>{
  const entries=list.filter(m=>kinds.includes(m.kind));
  if(!entries.length)return '';
  return `<section class="material-group"><h4 class="material-group-title">${label}<span>${entries.length}</span></h4><div class="material-list">${entries.map(m=>`<article class="material-card"><span class="material-kind">${safe(m.kind)}</span><h5>${safe(m.title)}</h5>${m.byline?`<p class="material-byline">${safe(m.byline)}</p>`:''}${m.note?`<p class="material-note">${safe(m.note)}</p>`:''}<div class="material-actions">${m.links.map(l=>`<a href="${safe(l.url)}" target="_blank" rel="noopener noreferrer" aria-label="${safe(l.label)}: ${safe(m.title)} (abre em nova aba)">${safe(l.label)} <span aria-hidden="true">↗</span></a>`).join('')}</div></article>`).join('')}</div></section>`;
 }).join('');
 return `<section class="materials-section" aria-labelledby="materials-title"><div class="materials-heading"><h3 id="materials-title">Para ler, assistir ou jogar</h3><span>${list.length} ${list.length===1?'material':'materiais'}</span></div>${markup}<p class="material-disclaimer">O ano indica a estreia original do filme ou da série. As fichas distinguem adaptações, expansões e releituras ligadas a este ramo. “Onde assistir” consulta o JustWatch Brasil, com opções de assinatura, aluguel ou compra quando disponíveis. Nas lojas, confira a edição e o idioma. Preços, estoque e disponibilidade variam.</p></section>`;
}
function showDetail(id,trigger){
 const n=nodes[id];if(!n)return;if(trigger)lastTrigger=trigger;
 const edges=allEdges(),incoming=edges.filter(e=>e.to===id),outgoing=edges.filter(e=>e.from===id);
 dialog.className='tone-'+n.tone;
 document.getElementById('detail-content').innerHTML=`<p class="detail-kicker">${safe(n.kind)} · ${safe(n.date)}</p><h2 id="detail-title" class="detail-title" tabindex="-1">${safe(n.title)}</h2><p class="detail-author">${safe(n.author)}</p>${materialsMarkup(id)}<div class="detail-section"><h3>A obra na árvore</h3><p class="detail-body">${safe(n.body)}</p></div>${incoming.length?`<div class="detail-section"><h3>De onde vêm as influências</h3><div class="relation-list">${relationMarkup(incoming,true)}</div></div>`:''}${outgoing.length?`<div class="detail-section"><h3>Conexões que seguem adiante</h3><div class="relation-list">${relationMarkup(outgoing,false)}</div></div>`:''}<div class="detail-section"><h3>Fontes para continuar</h3><div class="source-links">${n.refs.map(key=>`<a href="${safe(sources[key][1])}" target="_blank" rel="noopener noreferrer">${safe(sources[key][0])} ↗</a>`).join('')}</div></div><p class="dialog-footnote">Conexões selecionadas: esta ficha não esgota as influências da obra.</p>`;
 if(!dialog.open){dialog.showModal();document.body.classList.add('modal-open');}
 dialog.scrollTop=0;document.getElementById('detail-title').focus({preventScroll:true});
 svg.querySelectorAll('.edge').forEach(p=>p.classList.toggle('emphasized',p.dataset.from===id||p.dataset.to===id));
}
nodeContainer.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)showDetail(b.dataset.id,b);});
document.querySelector('.chapter-tabs').addEventListener('click',e=>{const t=e.target.closest('[data-chapter]');if(t)chooseChapter(t.dataset.chapter);});
document.querySelector('.chapter-tabs').addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('[role=tab]')];let index=tabs.indexOf(document.activeElement);if(index<0)return;if(e.key==='ArrowRight')index=(index+1)%tabs.length;else if(e.key==='ArrowLeft')index=(index+tabs.length-1)%tabs.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=tabs.length-1;else return;e.preventDefault();chooseChapter(tabs[index].dataset.chapter,true);});
dialog.querySelector('.close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{const b=e.target.closest('[data-related]');if(b)showDetail(b.dataset.related);if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close();}});
dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');svg.querySelectorAll('.emphasized').forEach(p=>p.classList.remove('emphasized'));lastTrigger?.focus({preventScroll:true});});
mobile.addEventListener('change',render);
let raf;new ResizeObserver(()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(drawConnections);}).observe(tree);
render();
